### ISSUE TITLE
[Feat] 서치 결과 뷰 UI 구현

### ISSUE THREAD

**Issue by seuriseuljjeok** [DO-SOPT-APP6-NAVER-MAP/NAVER-MAP-iOS#4]
## 🔥 Issue 내용
서치 결과 뷰 UI 구현

## ✅ To-do
- [x] 상단 서치바

- [x] 지도
   - [x] Map View
   - [x] 좌측 상단 버튼 그룹
   - [x] 우측 하단 '위치' 버튼

- [x] BottomSheet
   - [x] 드래그 & 예약/주문/pay 아이콘
   - [x] 검색 정보
   - [x] 검색 관련 이미지
   - [x] 하단 기타 기능
